<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TheIsleOverlay.Core\TheIsleOverlay.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\pro-update-public-key.pem"
                      LogicalName="TheIsleOverlay.ProClient.pro-update-public-key.pem" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
